### ISSUE TITLE
Crashing 1 instance of firejail crashes other instances

### ISSUE THREAD

**Issue by ThomasTJdev** [juancarlospaco/nim-firejail#3]
## Problem
Different instances of firejails can crash each other.

## System
- when running 2 or more instances of NimWC with firejail
- firejail version 0.9.58
- nim 0.19.4
- 4.15.0-1032-aws #34-Ubuntu x86_64
- using default settings in `nimwc/config/config.cfg`

## Test
- Instance 1 = **web[1]**
- Instance 2 = **web[2]**

If **web[1]** needs access to `/mnt`, but the settings is set to `noMnt=true`, this will cause a crash inside NimWC due not having access to storage. This results in a restart of **web[1]**. But it will also cause **web[2]** to crash.

### web[1] crash output:
```
Mar 02 11:19:43 development nimwc_web2[26548]: starting application
Mar 02 11:19:43 development nimwc_web2[26548]: LD_PRELOAD=(null)
Mar 02 11:19:43 development nimwc_web2[26548]: execvp argument 0: /home/ubuntu/nim/web2/nimwcpkg/nimwc_main
Mar 02 11:19:43 development nimwc_web2[26548]: files_efs.nim(23)        files_efs
Mar 02 11:19:43 development nimwc_web2[26548]: os.nim(1012)             existsOrCreateDir
Mar 02 11:19:43 development nimwc_web2[26548]: os.nim(991)              rawCreateDir
Mar 02 11:19:43 development nimwc_web2[26548]: oserr.nim(66)            raiseOSError
Mar 02 11:19:43 development nimwc_web2[26548]: Error: unhandled exception: Permission denied; Additional info: "/mnt/efs/web2" [OSError]
Mar 02 11:19:43 development nimwc_web2[26548]: D, [2019-03-02T11:19:43] -- nimwc_main: Rolling File Logger logs at: /home/ubuntu/nim/web2/nimwcpkg/nimwc_main.log
Mar 02 11:19:43 development nimwc_web2[26548]: I, [2019-03-02T11:19:43] -- nimwc_main: Checking that required 'files' folders exists.
Mar 02 11:19:43 development firejail[26601]: exiting...
Mar 02 11:19:43 development nimwc_web2[26548]: Parent is shutting down, bye...
Mar 02 11:19:43 development nimwc_web2[26548]: Drop privileges: pid 26582, uid 1000, gid 1000, nogroups 0
Mar 02 11:19:43 development nimwc_web2[26548]: Supplementary groups: 29 44
```

### web[2] crash output:
```
Mar 02 11:19:58 development firejail[26861]: exiting...
Mar 02 11:19:58 development nimwc[25983]: Parent is shutting down, bye...
Mar 02 11:19:58 development nimwc[25983]: Drop privileges: pid 26845, uid 1000, gid 1000, nogroups 0
Mar 02 11:19:58 development nimwc[25983]: Supplementary groups: 29 44
Mar 02 11:19:58 development nimwc[25983]: *** Starting xvfb server: "Xvfb" ":487" "-screen" "0" "800x600x24" ***
Mar 02 11:19:58 development nimwc[25983]: *** Stating xvfb client: "firejail" "--noprofile" "--debug" "--caps" "--keep-dev-shm" "--no3d
Mar 02 11:19:58 development nimwc[25983]: xvfb server pid 26846
Mar 02 11:19:59 development nimwc[25983]: 2019-03-02T11:19:58+00:00: Restarting in 1 second.
Mar 02 11:19:59 development nimwc[25983]: firejail --noprofile --debug   --caps --keep-dev-shm  --no3d --nodbus --nodvd   --noroot --no
Mar 02 11:20:00 development nimwc[25983]: *** Attaching to Xvfb display 210 ***
Mar 02 11:20:00 development nimwc[25983]: Drop privileges: pid 26907, uid 1000, gid 1000, nogroups 0
Mar 02 11:20:00 development nimwc[25983]: Supplementary groups: 29 44
Mar 02 11:20:00 development nimwc[25983]: *** Starting xvfb server: "Xvfb" ":210" "-screen" "0" "800x600x24" ***
Mar 02 11:20:00 development nimwc[25983]: *** Stating xvfb client: "firejail" "--noprofile" "--debug" "--caps" "--keep-dev-shm" "--no3d
Mar 02 11:20:00 development nimwc[25983]: xvfb server pid 26908
Mar 02 11:20:00 development nimwc[25983]: Warning: Sandbox name changed to nimwc_main-2
Mar 02 11:20:00 development nimwc[25983]: DISPLAY=:210 parsed as 210
Mar 02 11:20:00 development nimwc[25983]: Parent pid 26918, child pid 26919
Mar 02 11:20:00 development nimwc[25983]: Building quoted command line: '/home/ubuntu/nim/web2/nimwcpkg/nimwc_main'
Mar 02 11:20:00 development nimwc[25983]: Command name #nimwc_main#
```

**Comment by juancarlospaco** [comment]
So you are running 2 from the same Storage folder :grey_question: 
More like a wrong config than a bug, but sure something needs to be changed.

**Comment by ThomasTJdev** [comment]
> So you are running 2 from the same Storage folder 
> More like a wrong config than a bug, but sure something needs to be changed.

No, it's running in different folders and using different storage locations

- /home/user/nim/web[1]
- /home/user/nim/web[2]

**Comment by juancarlospaco** [comment]
If you Uncheck the `noMnt` option on http://127.0.0.1:7000/settings/firejail or in the `config.cfg` it works :grey_question: 

Maybe we can just default `noMnt` as OFF.

**Comment by ThomasTJdev** [comment]
> If you Uncheck the `noMnt` option on http://127.0.0.1:7000/settings/firejail or in the `config.cfg` it works

Yes, no problem if I set `noMnt=false` cause then NimWC does not crash.

**Comment by juancarlospaco** [comment]
Fix can be:
Set it OFF by default.
Add to the Firejail page `Only Enable when 1 single instance running per server`.

**Comment by ThomasTJdev** [comment]
This is just because NimWC fails if the storage is not accessible, but what if NimWC fails by something else, will that still crash the other instances? I have not tested other scenarios.

I'm now running 5 instances on the same server - no problem. The problem was only, when 1 of the instances failed. Is there some internal binding between the different firejail instances?

**Comment by juancarlospaco** [comment]
Firejail wont bind to other Firejails.
I dont think they will collide each other. It was just kinda race condition on the isolated folder access.
